### PR TITLE
Fix AssertTrueFalseToSpecificMethodRector

### LINKED ISSUE #334: [PHPUnit] in_array with third is wrong refactory
Bug report:
```diff
-assertTrue(in_array($foo, [$bar], true))
+assertContains($foo, $bar, true)
```

The third arguments shouldn't be include.

### PR DESCRIPTION
**Pull request by carusogabriel**
Fixes #334

### CODE REVIEW

File: tests/Rector/Contrib/PHPUnit/SpecificMethod/AssertTrueFalseToSpecificMethodRector/Wrong/wrong.php.inc [hunk 1]
```diff
@@ -5,7 +5,7 @@ final class MyTest extends \PHPUnit\Framework\TestCase
     public function test()
     {
         $this->assertTrue(array_key_exists('...', ['...']), 'argument');
-        $this->assertTrue(in_array('...', ['...']), 'argument');
+        $this->assertTrue(in_array('...', ['...'], true), 'argument');
```
Comment (TomasVotruba) [inline tests/Rector/Contrib/PHPUnit/SpecificMethod/AssertTrueFalseToSpecificMethodRector/Wrong/wrong.php.inc]: Could you also add 

```php
$this->assertTrue(in_array('...', ['...']), 'argument');
```

so we know this case is still covered?

Comment (carusogabriel) [reply tests/Rector/Contrib/PHPUnit/SpecificMethod/AssertTrueFalseToSpecificMethodRector/Wrong/wrong.php.inc]: I'll revert the `array_search`, so we know that both cases are covered, without expand our tests :)
