### PR TITLE
fix nested comment in nested foreach to if

### LINKED ISSUE #3504: I found a bug with the ChangeNestedForeachIfsToEarlyContinueRector
# Bug Report

| ChangeNestedForeachIfsToEarlyContinueRector Bug| When there is a comment inside the if statement before the brace, it misses a brace creating the early continue statement. |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v0.7.29              |
| Installed as   | composer dependency                    |

## Minimal PHP Code Causing Issue
```
class CommentInsideIfStatement
{
    public function run()
    {
        $items = [];
        foreach ($values as $value) {
            if ($value === 5) //why am I doing this?
            {
                if ($value2 === 10) {
                    $items[] = 'maybe';
                }
            }
        }
    }
}
```
 https://getrector.org/demo/9757fa4a-ed15-4130-8bdc-ae150305360e

## Expected Behaviour
```
class CommentInsideIfStatement
{
    public function run()
    {
        $items = [];
        foreach ($values as $value) {
            if ($value !== 5) {
                //why am I doing this?
                continue;
            }
            if ($value2 !== 10) {
                continue;
            }
            $items[] = 'maybe';
        }
    }
}
```

Rector is producing invalid php when I try this.

https://github.com/rectorphp/rector/pull/3503

### PR DESCRIPTION
**Pull request by TomasVotruba**
Closes #3504﻿

### CODE REVIEW

File: rules/solid/tests/Rector/Foreach_/ChangeNestedForeachIfsToEarlyContinueRector/Fixture/comment_inside_if_statement.php.inc [hunk 1]
```diff
@@ -27,16 +27,16 @@ namespace Rector\SOLID\Tests\Rector\Foreach_\ChangeNestedForeachIfsToEarlyContin
...
         $items = [];
 
         foreach ($values as $value) {
             if ($value !== 5) {
-                //why am I doing this?
                 continue;
             }
-            if ($value2 !== 10) {
+            // why am I doing this?
+            if ($value !== 10) {
```
Comment (TomasVotruba) [inline rules/solid/tests/Rector/Foreach_/ChangeNestedForeachIfsToEarlyContinueRector/Fixture/comment_inside_if_statement.php.inc:39]: This is how php-parser sees the comment before `{`
