### PR TITLE
Ignore special class names when using Option::AUTO_IMPORT_NAMES

### LINKED ISSUE #5426: Class App\\AnonymousClass1c24b64c37740a293d326ceb80ab1552 was not found while trying to analyse it
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.9.18              |
| Installed as   | prefixed                           |

I'm trying to run the PHP 7.0 set and getting a very weird error:
```
Analyze error: \"Class App\\AnonymousClass1c24b64c37740a293d326ceb80ab1552 was not found while trying to analyse it - discovering symbols is probably not configured properly.\". Include your files in \"$parameters->set(Option::AUTOLOAD_PATHS, [...]);\
```

that is caused by this code (that I shrunk down to bare minimum to reproduce it):
```php
<?php

declare(strict_types=1);

namespace App;

use Exception;

final class Bug
{
    public function weird() : void
    {
        $exception = new class() extends Exception {
            public static function create() : self
            {
                $exception = new self();

                return $exception;
            }
        };
    }
}
```

Important to reproduce: you must be in a namespace + use anonymous class.

I have no idea what causes this error. I ran it locally with `--debug` and it didn't give me anything valuable:
```
vendor/bin/rector process src/Bug.php --debug
Rector 0.9.18
Config file: rector.php

[parsing] src/Bug.php
[refactoring] src/Bug.php
    [applying] Rector\Renaming\Rector\Name\RenameClassRector
    [applying] Rector\Renaming\Rector\FileWithoutNamespace\PseudoNamespaceToNamespaceRector
    [applying] Rector\PHPUnit\Rector\Class_\RemoveDataProviderTestPrefixRector
    [applying] Rector\PHPUnit\Rector\Class_\TestListenerToHooksRector
    [applying] Rector\PHPUnit\Rector\Class_\AddProphecyTraitRector
    [applying] Rector\Php56\Rector\FunctionLike\AddDefaultValueForUndefinedVariableRector
    [applying] Rector\Php70\Rector\ClassMethod\Php4ConstructorRector
    [applying] Rector\Php70\Rector\FunctionLike\ExceptionHandlerTypehintRector
    [applying] Rector\Renaming\Rector\MethodCall\RenameMethodRector
    [applying] Rector\PHPUnit\Rector\ClassMethod\ExceptionAnnotationRector
    [applying] Rector\Renaming\Rector\ClassMethod\RenameAnnotationRector
    [applying] Rector\TypeDeclaration\Rector\ClassMethod\AddParamTypeDeclarationRector
    [applying] Rector\TypeDeclaration\Rector\ClassMethod\AddReturnTypeDeclarationRector
    [applying] Rector\MysqlToMysqli\Rector\Assign\MysqlAssignToMysqliRector
    [applying] Rector\Php70\Rector\Assign\ListSplitStringRector
    [applying] Rector\Php70\Rector\Assign\ListSwapArrayOrderRector
    [applying] Rector\Php53\Rector\Variable\ReplaceHttpServerVarsByServerRector
    [applying] Rector\Php70\Rector\Variable\WrapVariableVariableNameInCurlyBracesRector
[post rectors] src/Bug.php
[printing] src/Bug.php



 [ERROR] Could not process "src/Bug.php" file, due to:
         "Analyze error: "Class App\AnonymousClass21dfecc387e6b0ae3223745c946461c7 was not found while trying to
         analyse it - discovering symbols is probably not configured properly.". Include your files in
         "$parameters->set(Option::AUTOLOAD_PATHS, [...]);" in "rector.php" config.
         See https://github.com/rectorphp/rector#configuration".

```

If you can point me in the right direction I can try and fix it via a PR. 

## Minimal PHP Code Causing Issue

https://getrector.org/demo/9d0ad78d-3b89-4f60-bfc1-9b3172a1d715
## Expected Behaviour

No error.

### PR DESCRIPTION
**Pull request by ruudk**
Fixes #5426

This makes sure that special class names like `self, parent, static` are not automatically imported.

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Test can be placed in test any test case, that tests auto imports names:

```php
$this->setParameter(Option::AUTO_IMPORT_NAMES, true);
```

Ideally the one that caused the bug in your project

File: rules/code-quality/tests/Rector/Return_/SimplifyUselessVariableRector/Fixture/skip_special_class_name.php.inc [hunk 1]
```diff
@@ -0,0 +1,45 @@
+<?php
+
+namespace Rector\Naming\Tests\Rector\ClassMethod\RenameVariableToMatchNewTypeRector\Fixture;
+
+use Exception;
+
+final class SkipSpecialClassName
```
Comment (samsonasik) [inline rules/code-quality/tests/Rector/Return_/SimplifyUselessVariableRector/Fixture/skip_special_class_name.php.inc:7]: can be `DoNotChangeSpecialClassName` or `DoNotImportSpecialClassName`

Comment (ruudk) [reply rules/code-quality/tests/Rector/Return_/SimplifyUselessVariableRector/Fixture/skip_special_class_name.php.inc]: Thanks, fixed it before I saw this.

**Comment by ruudk** [comment]
PR is ready now ✅

File: packages/post-rector/src/Rector/NameImportingPostRector.php [hunk 2]
```diff
@@ -85,6 +85,10 @@ private function processNodeName(Name $name): ?Node
     {
         $importName = $this->getName($name);
 
+        if ($name->isSpecialClassName()) {
```
Comment (samsonasik) [inline packages/post-rector/src/Rector/NameImportingPostRector.php:88]: this `if` seems can be moved up before `$importName` definition.

Comment (ruudk) [reply packages/post-rector/src/Rector/NameImportingPostRector.php:86]: Fixed!

**Comment by ruudk** [comment]
Applied feedback!

**Review by samsonasik — APPROVED** [review]

**Comment by TomasVotruba** [comment]
Thank you :+1:
