### PR TITLE
Fix AssertPropertyExistsRector

### LINKED ISSUE #420: [BUG] Call toString on null at AssertPropertyExistsRector
The `AssertPropertyExistsRector` needs to be update. It assumes that the first argument of `property_exists` is a class, when the following code is also possible:
```php
$response = new Response();
$response->foo = 'bar';

$this->assertFalse(property_exists($response, 'foo'));
```

### PR DESCRIPTION
**Pull request by mssimi**
Closes #420

### CODE REVIEW

**Comment by TomasVotruba** [comment]
@carusogabriel Could you review and merge it? You have better knowledge of these :)

File: src/Rector/Contrib/PHPUnit/SpecificMethod/AssertPropertyExistsRector.php [hunk 1]
```diff
@@ -73,7 +82,7 @@ public function isCandidate(Node $node): bool
             return false;
         }
 
-        if (! $this->methodCallAnalyzer->isMethods($node, array_keys($this->renameMethodsMap))) {
+        if (! $this->methodCallAnalyzer->isMethods($node, ['assertTrue', 'assertFalse'])) {
```
Comment (carusogabriel) [inline src/Rector/Contrib/PHPUnit/SpecificMethod/AssertPropertyExistsRector.php]: We can use either `$renameMethodsWithClassMap` or `$renameMethodsWithObjectMap` here

Comment (mssimi) [reply src/Rector/Contrib/PHPUnit/SpecificMethod/AssertPropertyExistsRector.php]: Since there are now two maps, it puts me into position to choose one of those. I find this clearer and more efficient as I don't have to transform keys to array.

**Comment by TomasVotruba** [comment]
Thank you both :+1:
