### PR TITLE
[PHPUnit] Fix CreateMockToCreateStubRector outside PHPUnit test case

### LINKED ISSUE #3157: createMockToCreateStub rector fixes too many methods
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.7.11             |
| Installed as   | rector/rector-prefixed                      |

I tried using the rector on https://github.com/sonata-project/SonataAdminBundle, and here is the result: https://github.com/sonata-project/SonataAdminBundle/pull/6043#discussion_r407072534

## Minimal PHP Code Causing Issue
Could not reproduce it on the demo, because it would imply defining several interfaces
```php
<?php

declare(strict_types=1);

namespace Sonata\AdminBundle\Tests\Admin;

use PHPUnit\Framework\TestCase;
use Sonata\AdminBundle\Model\ModelManagerInterface;
use Sonata\DatagridBundle\Datagrid\DatagridInterface;

class AdminTest extends TestCase
{
    public function testGetFilterFieldDescription(): void
    {
        $modelManager = $this->createStub(ModelManagerInterface::class);
        $modelManager
            ->method('getNewFieldDescriptionInstance')
            ->willReturnCallback(static function () {
            });

        $datagrid = $this->createMock(DatagridInterface::class);
        $datagrid->expects($this->once())
            ->method('getPager');
    }
}

```
## Expected Behaviour

The change to `createStub` should not be done

### PR DESCRIPTION
**Pull request by TomasVotruba**
Closes #3157

### CODE REVIEW

File: rules/phpunit/tests/Rector/MethodCall/CreateMockToCreateStubRector/Fixture/skip_sonata_expects.php.inc [hunk 1]
```diff
@@ -0,0 +1,17 @@
...
+{
+    public function testItBehavesAsExpected(): void
+    {
+        $datagrid = $this->createMock(DatagridInterface::class);
+
+        $datagrid->expects($this->once())
+            ->method('getPager')
+            ->willReturn($pager);
+    }
+}
```
Comment (TomasVotruba) [inline rules/phpunit/tests/Rector/MethodCall/CreateMockToCreateStubRector/Fixture/skip_sonata_expects.php.inc:17]: @greg0ire I've just added test case for:
https://github.com/rectorphp/rector/issues/3157

And it is skipped.

If the problem still remains, we need either failing test case (like this fixture, just failing) or failing demo. We're unable to fix that without any replicable proof.
