### PR TITLE
Fix assert choice tag value node with class constant reference

### LINKED ISSUE #3044: How to disable inlining of a constant in annotation
# Question
How to disable this?

```diff
    public const RATINGS_DISCRIMINATOR_MAP = [
        '5star' => FiveStar::class,
        '4star' => FourStar::class,
    ];
     /**
      * @Assert\NotBlank()
-     * @Assert\Choice(choices=App\Entity\Rating\Rating::RATINGS_DISCRIMINATOR_MAP)
+     * @Assert\Choice({"5star":"App\Entity\Rating\FiveStar", "4star":"App\Entity\Rating\FourStar"})
      */
```

### PR DESCRIPTION
**Pull request by TomasVotruba**
Closes #3044

### CODE REVIEW

File: packages/better-php-doc-parser/src/PhpDocNode/Symfony/Validator/Constraints/AssertChoiceTagValueNode.php [hunk 1]
```diff
@@ -71,4 +88,41 @@ public function getShortName(): string
...
+        if ($this->hasChoiceKeywordExplicit) {
+            $content = 'choices=';
+        }
+
+        return $content . $this->originalChoiceContent;
+    }
+
+    private function resolveOriginalChoiceContent(string $annotationContent): ?string
+    {
+        $matches = Strings::match($annotationContent, '#(\(choices=|\()(?<choice_content>.*?)(\)|,)#ms');
```
Comment (SergeC) [inline packages/better-php-doc-parser/src/PhpDocNode/Symfony/Validator/Constraints/AssertChoiceTagValueNode.php]: I'm not sure `choices` must be hardcoded since it is related to my use-case and it may not work for others.

Comment (TomasVotruba) [reply packages/better-php-doc-parser/src/PhpDocNode/Symfony/Validator/Constraints/AssertChoiceTagValueNode.php]: How would you implement it better?

Comment (SergeC) [reply packages/better-php-doc-parser/src/PhpDocNode/Symfony/Validator/Constraints/AssertChoiceTagValueNode.php]: https://getrector.org/demo/54a3163e-13d1-4a01-8101-f32340bcd095 I changed `choices ` to `groups` and issue is back as expected. I would try to remove `choices` from regexp and detect `=` sign. If `=CONST`.

Comment (TomasVotruba) [reply packages/better-php-doc-parser/src/PhpDocNode/Symfony/Validator/Constraints/AssertChoiceTagValueNode.php]: Could you send PR?

Comment (SergeC) [reply packages/better-php-doc-parser/src/PhpDocNode/Symfony/Validator/Constraints/AssertChoiceTagValueNode.php]: I'm not familiar with how Rector works under the hood. I can provide use cases and do manual testing. My point is not to hardcode `choices` because variable name could be any other or not set.

Comment (TomasVotruba) [reply packages/better-php-doc-parser/src/PhpDocNode/Symfony/Validator/Constraints/AssertChoiceTagValueNode.php]: This part is not in Rector, but in doctrine/annotations.
The best would be to disable constant value resolution in there.
This is just a bad band-aid on doctrine design choice.

If we can somehow disable this line: https://github.com/doctrine/annotations/blob/904dca4eb10715b92569fbcd79e201d5c349b6bc/lib/Doctrine/Common/Annotations/DocParser.php#L981
and `return $identifier;` instead, it would solve all these cases.

Comment (SergeC) [reply packages/better-php-doc-parser/src/PhpDocNode/Symfony/Validator/Constraints/AssertChoiceTagValueNode.php]: I suggest reverting this Pull Request, reopen an issue and think about solving this issue together. May be Rector can parse a file, find annotations with constants and exclude them with `setIgnoredAnnotationNames` https://github.com/doctrine/annotations/blob/904dca4eb10715b92569fbcd79e201d5c349b6bc/lib/Doctrine/Common/Annotations/DocParser.php#L257 ?

Comment (SergeC) [reply packages/better-php-doc-parser/src/PhpDocNode/Symfony/Validator/Constraints/AssertChoiceTagValueNode.php]: Here is a test https://github.com/doctrine/annotations/blob/dc296632db0500c7bd5144161cf96708f61059ff/tests/Doctrine/Tests/Common/Annotations/DocParserTest.php#L1055

Comment (TomasVotruba) [reply packages/better-php-doc-parser/src/PhpDocNode/Symfony/Validator/Constraints/AssertChoiceTagValueNode.php]: It seems unrelated.
Could you update your annotation code with that?

Comment (SergeC) [reply packages/better-php-doc-parser/src/PhpDocNode/Symfony/Validator/Constraints/AssertChoiceTagValueNode.php]: Sorry, I didn't get your point. What should I do? Please provide more details.

Comment (TomasVotruba) [reply packages/better-php-doc-parser/src/PhpDocNode/Symfony/Validator/Constraints/AssertChoiceTagValueNode.php]: Working solution for your use case with "choice" annotation.

Any gist would do.

Comment (SergeC) [reply packages/better-php-doc-parser/src/PhpDocNode/Symfony/Validator/Constraints/AssertChoiceTagValueNode.php]: The `setIgnoredAnnotationNames` method doesn't work. Even Doctrine's test doesn't work properly. There is a patch that looks relevant but it is not released yet. https://github.com/doctrine/annotations/pull/244

Comment (SergeC) [reply packages/better-php-doc-parser/src/PhpDocNode/Symfony/Validator/Constraints/AssertChoiceTagValueNode.php]: Opened an issue to find it out https://github.com/doctrine/annotations/issues/312

Comment (TomasVotruba) [reply packages/better-php-doc-parser/src/PhpDocNode/Symfony/Validator/Constraints/AssertChoiceTagValueNode.php]: How did you verify this would help in our case?

Any reproducible code would help

**Comment by TomasVotruba** [comment]
Surpassed by #3134
