### PR TITLE
[NetteToSymfony] Fix new route for already present annotation above method

### LINKED ISSUE #1049: [NetteToSymfony] Routes rector does not add @Route annotation when annotation already exists
I had one controller with `@todo` annotation containing comment, it was not processed by rector -> annotation was not added/extended.

### PR DESCRIPTION
**Pull request by TomasVotruba**
Closes #1049

### CODE REVIEW

File: packages/NetteToSymfony/src/Annotation/SymfonyRoutePhpDocTagNode.php [hunk 1]
```diff
@@ -3,18 +3,23 @@
 namespace Rector\NetteToSymfony\Annotation;
 
 use PHPStan\PhpDocParser\Ast\PhpDoc\PhpDocChildNode;
+use PHPStan\PhpDocParser\Ast\PhpDoc\PhpDocTagNode;
+use Symplify\BetterPhpDocParser\Attributes\Attribute\AttributeTrait;
+use Symplify\BetterPhpDocParser\Attributes\Contract\Ast\AttributeAwareNodeInterface;
 
-final class RouteTagValueNode implements PhpDocChildNode
+final class SymfonyRoutePhpDocTagNode extends PhpDocTagNode implements PhpDocChildNode, AttributeAwareNodeInterface
```
Comment (JanMikes) [inline packages/NetteToSymfony/src/Annotation/SymfonyRoutePhpDocTagNode.php]: It was this easy? Extending a class? :smile:

Comment (TomasVotruba) [reply packages/NetteToSymfony/src/Annotation/SymfonyRoutePhpDocTagNode.php]: Yes :D and bit of work in BetterPhpDocParser :) 
https://github.com/Symplify/Symplify/pull/1437/files
