### PR TITLE
[Php80] Skip ChangeSwitchToMatchRector on missed break

### LINKED ISSUE #5607: Rule ChangeSwitchToMatchRector works wrong
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.9.29              |
| Installed as   | composer dependency                           |

If in a `switch-case` body missed break statement the rector also converts it to short `match` construnction

## Minimal PHP Code Causing Issue

```
switch ($suffix) {
    /** @noinspection PhpMissingBreakStatementInspection */
    case 'M':
        $value *= 1024;
    case 'K':
        $value *= 1024;
        break;
}
```
converts to
```
match ($suffix) {
    'M' => $value *= 1024,
    'K' => $value *= 1024,
};
```

## Expected Behaviour

Rector should skip it

https://3v4l.org/S3vFa

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes #5607

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Thank you :clap:

File: rules/php80/src/NodeAnalyzer/SwitchAnalyzer.php [hunk 1]
```diff
@@ -12,17 +12,26 @@ final class SwitchAnalyzer
...
+        foreach ($switch->cases as $key => $case) {
+            if ($key === $totalCases - 1) {
                 return true;
             }
+
+            foreach ($case->stmts as $caseStmt) {
+                if ($caseStmt instanceof Break_) {
+                    continue 2;
+                }
+            }
```
Comment (roxblnfk) [inline rules/php80/src/NodeAnalyzer/SwitchAnalyzer.php:29]: I'm not sure the behavior will be appropriate in this rule. However, `continue;` (without arguments) behaves the same as ' break;`

See https://github.com/rectorphp/rector/issues/5646
