### PR TITLE
Fixes #4013 ConsoleExecuteReturnIntRector ignores already type casted variable

### LINKED ISSUE #4013: ConsoleExecuteReturnIntRector ignores already type casted variable
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.7.65              |
| Installed as   | composer dependency                      |

https://getrector.org/demo/9a18901a-b9d7-4545-97b9-53c5313cd65e

Bugged class: `\Rector\Symfony\Rector\ClassMethod\ConsoleExecuteReturnIntRector`

This is the result:

```diff
{
 		$initialized = parent::execute($input, $output);
         if (0 !== $initialized) {
-            return (int) $initialized;
+            return (int) (int) $initialized;
         }
 		
 		return 0;
 	}
 }
```

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes #4013

### CODE REVIEW

File: rules/symfony/tests/Rector/ClassMethod/ConsoleExecuteReturnIntRector/Fixture/skip-already-typehinted.php.inc [hunk 1]
```diff
@@ -0,0 +1,65 @@
...
+        $initialized = parent::execute($input, $output);
+        if (0 !== $initialized) {
+            return (int) $initialized;
+        }
+
+        return 0;
+    }
+}
+
+?>
```
Comment (TomasVotruba) [inline rules/symfony/tests/Rector/ClassMethod/ConsoleExecuteReturnIntRector/Fixture/skip-already-typehinted.php.inc:65]: In case the file should be untouched (no changes), this whole part is not needed

Comment (samsonasik) [reply rules/symfony/tests/Rector/ClassMethod/ConsoleExecuteReturnIntRector/Fixture/skip-already-typehinted.php.inc]: fixed.

File: rules/symfony/src/Rector/ClassMethod/ConsoleExecuteReturnIntRector.php [hunk 2]
```diff
@@ -112,6 +112,11 @@ private function addReturn0ToMethod(ClassMethod $classMethod): void
                 return null;
             }
 
+            if ($node->expr instanceof Int_) {
+                $hasReturn = true;
```
Comment (TomasVotruba) [inline rules/symfony/src/Rector/ClassMethod/ConsoleExecuteReturnIntRector.php:116]: I think this value is not need, since it's used bellow to return `$node`/null.

What do you think?

Comment (samsonasik) [reply rules/symfony/src/Rector/ClassMethod/ConsoleExecuteReturnIntRector.php]: yes, updated.

**Comment by samsonasik** [comment]
How about rename fixture file to `skip-return-already-typecasted.php.inc` ?

**Comment by TomasVotruba** [comment]
This is good enough, thank you :+1:
