### PR TITLE
Fix virtual property

### LINKED ISSUE #2086: [BetterPhpDocParser] SerializerTypePhpDocNodeFactory doesn't count with virtual props
No need for lengthy description.

This line https://github.com/rectorphp/rector/blob/598f228c6d12b74913f8915375abc8c222dddbd7/packages/BetterPhpDocParser/src/PhpDocNodeFactory/JMS/SerializerTypePhpDocNodeFactory.php#L24 is triggered for following code

```php
class Foo {
    /**
     * @Serializer\Type("boolean")
     * @Serializer\VirtualProperty
     */
    public function isBar(): bool
    {
        return true;
    }
}
```

Assumption that this annotation works only for properties is not correct.

### PR DESCRIPTION
**Pull request by TomasVotruba**
Closes #2086

### CODE REVIEW

File: packages/Php55/src/Rector/FuncCall/PregReplaceEModifierRector.php [hunk 1]
```diff
@@ -41,7 +41,7 @@ public function __construct(Parser $parser)
 
     public function getDefinition(): RectorDefinition
     {
-        return new RectorDefinition('The /e modifier is no longer supported, use preg_replace_callback instead ', [
+        return new RectorDefinition('The /e modifier is no longer supported, use preg_replace_callback instead', [
```
Comment (TomasVotruba) [inline packages/Php55/src/Rector/FuncCall/PregReplaceEModifierRector.php]: This finally fixes these repreated spaces in docs dump

File: utils/DocumentationGenerator/src/Command/DumpNodesCommand.php [hunk 2]
```diff
@@ -402,7 +402,7 @@ protected function execute(InputInterface $input, OutputInterface $output): int
 
                 $this->nodeInfoResult->addNodeInfo($category, new NodeInfo(
                     $nodeClass,
-                    $this->betterStandardPrinter->print($node),
+                    trim($this->betterStandardPrinter->print($node)),
```
Comment (TomasVotruba) [inline utils/DocumentationGenerator/src/Command/DumpNodesCommand.php]: This finally fixes these repreated spaces in docs dump
