### PR TITLE
[PHP 7.4] Make property nullable if not set in constructor

### LINKED ISSUE #3685: Another wrong typehint generated by Rector\Php74\Rector\Property\TypedPropertyRector
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.8.x-dev@f5daac              |
| Installed as   | prefixed Rector PHAR                      |

## Minimal PHP Code Causing Issue

https://getrector.org/demo/2ee820c5-c32c-459b-b0ef-358ef0b46cc1#result

## Expected Behaviour

```php
class MyClass
{
    private ?string $name = null;

    // ...
}
```

### PR DESCRIPTION
**Pull request by TomasVotruba**
Closes #3685

### CODE REVIEW

File: src/Application/RectorApplication.php [hunk 1]
```diff
@@ -122,7 +122,12 @@ public function runOnFileInfos(array $phpFileInfos): void
 
         if (! $this->symfonyStyle->isVerbose() && $this->configuration->showProgressBar()) {
             // why 5? one for each cycle, so user sees some activity all the time
-            $this->symfonyStyle->progressStart($fileCount * 5);
+            $stepMultiplier = 4;
+            if ($this->fileSystemFileProcessor->getFileSystemRectorsCount() !== 0) {
+                ++$stepMultiplier;
+            }
+
+            $this->symfonyStyle->progressStart($fileCount * $stepMultiplier);
```
Comment (TomasVotruba) [inline src/Application/RectorApplication.php]: @dobryy This is the fix for

image
