### PR TITLE
Fixes #4499 Code duplication on interface_exists and trait_exists inside if condition

### LINKED ISSUE #4499: Code gets duplicated
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.8.44             |
| Installed as   | composer dependency                     |

When running a set (any set) on file `stubs/Symfony/Component/VarDumper/Test/VarDumperTestTrait.php`, its code gets duplicated:

```diff
if (trait_exists('Symfony\Component\VarDumper\Test\VarDumperTestTrait\VarDumperTestTrait')) {
     return;
+}if (trait_exists('Symfony\Component\VarDumper\Test\VarDumperTestTrait\VarDumperTestTrait')) {
+    return;
 }
```

It doesn't indicate which is the applied rule

## Minimal PHP Code Causing Issue

https://getrector.org/demo/67559c76-b2e7-44bd-bca2-ec78a35d7f47#result

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

File: tests/Issues/Issue4499/DoNotDuplicateCode/DoNotDuplicateCodeTest.php [hunk 1]
```diff
@@ -0,0 +1,31 @@
...
+use Symplify\SmartFileSystem\SmartFileInfo;
+
+final class DoNotDuplicateCodeTest extends AbstractRectorTestCase
+{
+    /**
+     * @dataProvider provideData()
+     */
+    public function test(SmartFileInfo $fileInfo): void
+    {
+        @$this->doTestFileInfo($fileInfo);
```
Comment (samsonasik) [inline tests/Issues/Issue4499/DoNotDuplicateCode/DoNotDuplicateCodeTest.php:17]: this `@` is on purpose to avoid phpunit break on warning : 

```php
assert(): assert($itemStartPos >= 0 && $itemEndPos >= 0 && $itemStartPos >= $pos)
```

that came from `vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php` on line 759

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
I've added handle no bracket `{}` after if condition.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

File: src/PhpParser/Printer/BetterStandardPrinter.php [hunk 2]
```diff
@@ -505,6 +529,33 @@ private function detectTabOrSpaceIndentCharacter(array $stmts): void
         }
     }
 
+    private function cleanUpDuplicateContent(string $content): string
```
Comment (TomasVotruba) [inline src/PhpParser/Printer/BetterStandardPrinter.php:532]: This might looks like a random piece of code. Reference to the problem would help understand.


Could you refer the issue here?

Comment (samsonasik) [reply src/PhpParser/Printer/BetterStandardPrinter.php:535]: I've added  `@see https://github.com/rectorphp/rector/issues/4499` comment to reference issue.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

**Comment by TomasVotruba** [comment]
Thanks!

It should be still reported on php-parser as an issue.
It might be solves there in a clean way

**Comment by samsonasik** [comment]
The issue is happen when `if (interface_exists('InterfaceName')) {}` or `trait_exists('TraitName') { }` followed by `interface InterfaceName` or `trait TraitName`. 

@TomasVotruba could you handle report to php-parser ? Thank you.

**Comment by TomasVotruba** [comment]
I'll look into the issue for php-parser. Could you make an issue for that here, so I don't forget?

Thank you

**Comment by samsonasik** [comment]
@TomasVotruba Yes, I created issue https://github.com/rectorphp/rector/issues/4556 for it.

**Comment by TomasVotruba** [comment]
Thanks
