### PR TITLE
Symfony FormTypeInstanceToClassConstRector: Include AbstractController in allowed object types

### LINKED ISSUE #3570: Symfony: Cannot use FormTypeInstanceToClassConstRector within instances of AbstractController
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.7.37             |
| Installed as   | composer dependency                    |

I noticed that the `Rector\Symfony\Rector\MethodCall\FormTypeInstanceToClassConstRector` rector isn't working for controllers which extend `Symfony\Bundle\FrameworkBundle\Controller\AbstractController`. 

Having a look at the code, I think this is because the rector only runs on controllers which extend `Symfony\Bundle\FrameworkBundle\Controller\Controller`

Is is possible to get the rector to run on instances of `Symfony\Bundle\FrameworkBundle\Controller\AbstractController`?

## Minimal PHP Code Causing Issue
```php
<?php

namespace App\Controller;

use App\Type\RectorTestType;

class RectorTestController extends \Symfony\Bundle\FrameworkBundle\Controller\AbstractController
{
    public function rectorTestAction()
    {
        $this->createForm(new RectorTestType());
    }
}
```

## Expected Behaviour

```php
<?php

namespace App\Controller;

use App\Type\RectorTestType;

class RectorTestController extends \Symfony\Bundle\FrameworkBundle\Controller\AbstractController
{
    public function rectorTestAction()
    {
        $this->createForm(RectorTestType::class);
    }
}
```

### PR DESCRIPTION
**Pull request by andyexeter**
Fixes #3570 by adding `Symfony\Bundle\FrameworkBundle\Controller\AbstractController` as a valid object type.

### CODE REVIEW

File: rules/symfony/src/Rector/MethodCall/FormTypeInstanceToClassConstRector.php [hunk 1]
```diff
@@ -90,7 +91,7 @@ public function getNodeTypes(): array
      */
     public function refactor(Node $node): ?Node
     {
-        if ($this->isObjectType($node->var, Controller::class) && $this->isName($node->name, 'createForm')) {
+        if ($this->isObjectTypes($node->var, [Controller::class, AbstractController::class]) && $this->isName($node->name, 'createForm')) {
```
Comment (TomasVotruba) [inline rules/symfony/src/Rector/MethodCall/FormTypeInstanceToClassConstRector.php:94]: It might be fix for this case, but this can be acually broken when `Symfony\` gets prefixed in `rector.phar`.

Could you update the args so its strings?

```suggestion
        if ($this->isObjectTypes($node->var, ['Symfony\Bundle\FrameworkBundle\Controller\AbstractController', 'Symfony\Bundle\FrameworkBundle\Controller\Controller']) && $this->isName($node->name, 'createForm')) {
```

Comment (andyexeter) [reply rules/symfony/src/Rector/MethodCall/FormTypeInstanceToClassConstRector.php:94]: @TomasVotruba I will update.

There are other Symfony imports in this class:

Symfony\Component\Form\FormBuilderInterface
Symfony\Component\Form\FormInterface
Symfony\Component\OptionsResolver\OptionsResolver

Do these also need to be updated?

Comment (TomasVotruba) [reply rules/symfony/src/Rector/MethodCall/FormTypeInstanceToClassConstRector.php:94]: Yes. That would be great!

**Comment by TomasVotruba** [comment]
Thank you
