### PR TITLE
[PHP 8.0] Skip exception in match, must be expr

### LINKED ISSUE #4963: ChangeSwitchToMatchRector: Should not happen exception 🙂
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v0.9.5 (invoke `vendor/bin/rector --version`)              |
| Installed as   | composer dependency / prefixed Rector                           |

ChangeSwitchToMatchRector fails when there is a combination of throws & function in another branch.

## Minimal PHP Code Causing Issue

https://getrector.org/demo/2cd01685-49d1-4f5f-96aa-09be6d4207b5

```
    [applying] Rector\Php80\Rector\Switch_\ChangeSwitchToMatchRector
PHP Fatal error:  Uncaught Rector\Core\Exception\ShouldNotHappenException: Look at "Rector\Php80\Rector\Switch_\ChangeSwitchToMatchRector::createMatchArmsFromCases()" on line 178 in /var/www/html/vendor/rector/rector/rules/php80/src/Rector/Switch_/ChangeSwitchToMatchRector.php:178
Stack trace:
#0 /var/www/html/vendor/rector/rector/rules/php80/src/Rector/Switch_/ChangeSwitchToMatchRector.php(108): Rector\Php80\Rector\Switch_\ChangeSwitchToMatchRector->createMatchArmsFromCases(Array)
#1 /var/www/html/vendor/rector/rector/src/Rector/AbstractRector.php(231): Rector\Php80\Rector\Switch_\ChangeSwitchToMatchRector->refactor(Object(PhpParser\Node\Stmt\Switch_))
#2 /var/www/html/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(200): Rector\Core\Rector\AbstractRector->enterNode(Object(PhpParser\Node\Stmt\Switch_))
#3 /var/www/html/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(114): PhpParser\NodeTraverser->traverseArray(Array)
#4 /var/www/html/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\ClassMethod))
#5 /var/www/html/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(114): PhpParser\NodeTraverser->traverseArray(Array)
#6 /var/www/html/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Class_))
#7 /var/www/html/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(114): PhpParser\NodeTraverser->traverseArray(Array)
#8 /var/www/html/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode(Object(Rector\Core\PhpParser\Node\CustomNode\FileWithoutNamespace))
#9 /var/www/html/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(91): PhpParser\NodeTraverser->traverseArray(Array)
#10 /var/www/html/vendor/rector/rector/src/PhpParser/NodeTraverser/RectorNodeTraverser.php(116): PhpParser\NodeTraverser->traverse(Array)
#11 /var/www/html/vendor/rector/rector/src/Application/FileProcessor.php(143): Rector\Core\PhpParser\NodeTraverser\RectorNodeTraverser->traverse(Array)
#12 /var/www/html/vendor/rector/rector/src/Application/RectorApplication.php(212): Rector\Core\Application\FileProcessor->refactor(Object(Symplify\SmartFileSystem\SmartFileInfo))
#13 /var/www/html/vendor/rector/rector/src/Application/RectorApplication.php(227): Rector\Core\Application\RectorApplication->Rector\Core\Application\{closure}(Object(Symplify\SmartFileSystem\SmartFileInfo))
#14 /var/www/html/vendor/rector/rector/src/Application/RectorApplication.php(213): Rector\Core\Application\RectorApplication->tryCatchWrapper(Object(Symplify\SmartFileSystem\SmartFileInfo), Object(Closure), 'refactoring')
#15 /var/www/html/vendor/rector/rector/src/Application/RectorApplication.php(138): Rector\Core\Application\RectorApplication->refactorNodesWithRectors(Array)
#16 /var/www/html/vendor/rector/rector/src/Console/Command/ProcessCommand.php(207): Rector\Core\Application\RectorApplication->runOnFileInfos(Array)
#17 /var/www/html/vendor/symfony/console/Command/Command.php(255): Rector\Core\Console\Command\ProcessCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /var/www/html/vendor/rector/rector/src/Console/Command/AbstractCommand.php(44): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /var/www/html/vendor/symfony/console/Application.php(971): Rector\Core\Console\Command\AbstractCommand->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /var/www/html/vendor/symfony/console/Application.php(290): Symfony\Component\Console\Application->doRunCommand(Object(Rector\Core\Console\Command\ProcessCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /var/www/html/vendor/rector/rector/src/Console/ConsoleApplication.php(115): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /var/www/html/vendor/symfony/console/Application.php(166): Rector\Core\Console\ConsoleApplication->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /var/www/html/vendor/rector/rector/bin/rector.php(75): Symfony\Component\Console\Application->run()
#24 /var/www/html/vendor/rector/rector/bin/rector(4): require_once('/var/www/html/v...')
#25 {main}
  thrown in /var/www/html/vendor/rector/rector/rules/php80/src/Rector/Switch_/ChangeSwitchToMatchRector.php on line 178
Fatal error: Uncaught Rector\Core\Exception\ShouldNotHappenException: Look at "Rector\Php80\Rector\Switch_\ChangeSwitchToMatchRector::createMatchArmsFromCases()" on line 178 in /var/www/html/vendor/rector/rector/rules/php80/src/Rector/Switch_/ChangeSwitchToMatchRector.php:178
Stack trace:
#0 /var/www/html/vendor/rector/rector/rules/php80/src/Rector/Switch_/ChangeSwitchToMatchRector.php(108): Rector\Php80\Rector\Switch_\ChangeSwitchToMatchRector->createMatchArmsFromCases(Array)
#1 /var/www/html/vendor/rector/rector/src/Rector/AbstractRector.php(231): Rector\Php80\Rector\Switch_\ChangeSwitchToMatchRector->refactor(Object(PhpParser\Node\Stmt\Switch_))
#2 /var/www/html/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(200): Rector\Core\Rector\AbstractRector->enterNode(Object(PhpParser\Node\Stmt\Switch_))
#3 /var/www/html/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(114): PhpParser\NodeTraverser->traverseArray(Array)
#4 /var/www/html/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\ClassMethod))
#5 /var/www/html/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(114): PhpParser\NodeTraverser->traverseArray(Array)
#6 /var/www/html/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Class_))
#7 /var/www/html/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(114): PhpParser\NodeTraverser->traverseArray(Array)
#8 /var/www/html/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode(Object(Rector\Core\PhpParser\Node\CustomNode\FileWithoutNamespace))
#9 /var/www/html/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(91): PhpParser\NodeTraverser->traverseArray(Array)
#10 /var/www/html/vendor/rector/rector/src/PhpParser/NodeTraverser/RectorNodeTraverser.php(116): PhpParser\NodeTraverser->traverse(Array)
#11 /var/www/html/vendor/rector/rector/src/Application/FileProcessor.php(143): Rector\Core\PhpParser\NodeTraverser\RectorNodeTraverser->traverse(Array)
#12 /var/www/html/vendor/rector/rector/src/Application/RectorApplication.php(212): Rector\Core\Application\FileProcessor->refactor(Object(Symplify\SmartFileSystem\SmartFileInfo))
#13 /var/www/html/vendor/rector/rector/src/Application/RectorApplication.php(227): Rector\Core\Application\RectorApplication->Rector\Core\Application\{closure}(Object(Symplify\SmartFileSystem\SmartFileInfo))
#14 /var/www/html/vendor/rector/rector/src/Application/RectorApplication.php(213): Rector\Core\Application\RectorApplication->tryCatchWrapper(Object(Symplify\SmartFileSystem\SmartFileInfo), Object(Closure), 'refactoring')
#15 /var/www/html/vendor/rector/rector/src/Application/RectorApplication.php(138): Rector\Core\Application\RectorApplication->refactorNodesWithRectors(Array)
#16 /var/www/html/vendor/rector/rector/src/Console/Command/ProcessCommand.php(207): Rector\Core\Application\RectorApplication->runOnFileInfos(Array)
#17 /var/www/html/vendor/symfony/console/Command/Command.php(255): Rector\Core\Console\Command\ProcessCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /var/www/html/vendor/rector/rector/src/Console/Command/AbstractCommand.php(44): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /var/www/html/vendor/symfony/console/Application.php(971): Rector\Core\Console\Command\AbstractCommand->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /var/www/html/vendor/symfony/console/Application.php(290): Symfony\Component\Console\Application->doRunCommand(Object(Rector\Core\Console\Command\ProcessCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /var/www/html/vendor/rector/rector/src/Console/ConsoleApplication.php(115): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /var/www/html/vendor/symfony/console/Application.php(166): Rector\Core\Console\ConsoleApplication->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /var/www/html/vendor/rector/rector/bin/rector.php(75): Symfony\Component\Console\Application->run()
#24 /var/www/html/vendor/rector/rector/bin/rector(4): require_once('/var/www/html/v...')
#25 {main}
  thrown in /var/www/html/vendor/rector/rector/rules/php80/src/Rector/Switch_/ChangeSwitchToMatchRector.php on line 178

```

### PR DESCRIPTION
**Pull request by TomasVotruba**
Closes https://github.com/rectorphp/rector/issues/4963

### CODE REVIEW

File: rules/php80/tests/Rector/Switch_/ChangeSwitchToMatchRector/Fixture/skip_throwen_exception.php.inc [hunk 1]
```diff
@@ -0,0 +1,19 @@
...
+{
+    public function save(): void
+    {
+        switch ('deleted') {
+            case 'inserted':
+                echo '1';
+                break;
+
+            case 'deleted':
+                throw new \Exception();
```
Comment (jkuchar) [inline rules/php80/tests/Rector/Switch_/ChangeSwitchToMatchRector/Fixture/skip_throwen_exception.php.inc:15]: Exception is an expression since PHP8. https://www.amitmerchant.com/using-throw-as-an-expression-in-php8/ So This case would be skipped because of `echo` case, NOT because of thrown exception.

Comment (TomasVotruba) [reply rules/php80/tests/Rector/Switch_/ChangeSwitchToMatchRector/Fixture/skip_throwen_exception.php.inc:15]: Indeed, just in this case it's a `Stmt` in php-parser nodes: https://github.com/nikic/PHP-Parser/blob/master/lib/PhpParser/Node/Stmt/Throw_.php

I've just noticed there is also `Expr` version: https://github.com/nikic/PHP-Parser/blob/master/lib/PhpParser/Node/Expr/Throw_.php,
so the `Stmt\Throw_` would have to be converted to `Expr\Throw_`

Comment (TomasVotruba) [reply rules/php80/tests/Rector/Switch_/ChangeSwitchToMatchRector/Fixture/skip_throwen_exception.php.inc:15]: I think Rector could handle this, if we have failing test case.

Comment (jkuchar) [reply rules/php80/tests/Rector/Switch_/ChangeSwitchToMatchRector/Fixture/skip_throwen_exception.php.inc:15]: I think we cannot have failing test now, as rector skips case when there is an exception thrown. (even when it is possible to covert) https://getrector.org/demo/f92228fa-6001-4fcf-9fdc-35643c66bab6

Comment (TomasVotruba) [reply rules/php80/tests/Rector/Switch_/ChangeSwitchToMatchRector/Fixture/skip_throwen_exception.php.inc:15]: It would require to modify the rule :) do you want to try it?

Comment (jkuchar) [reply rules/php80/tests/Rector/Switch_/ChangeSwitchToMatchRector/Fixture/skip_throwen_exception.php.inc:15]: Not now, as I'm quite in hurry. I would like to fix my project before New Year. ;-)
