### PR TITLE
Fix Undefined offset in TypeFactory around flattenTypes calls

### LINKED ISSUE #5953: PHP Notice:  Undefined offset: in rector/packages/NodeTypeResolver/PHPStan/Type/TypeFactory.php on line 156
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.10.0              |
| Installed as   | composer dependency                           |

No code example included currently as I imagine this is something easily fixable (and perhaps no test would be written, as this isn't a failing rule?)

```
adam@adsh+wsl:~/dev/git/github/addwiki/addwiki (main)$ $ vendor/bin/rector
 214/792 [▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░░░░░░]  27%PHP Notice:  Undefined offset: 1 in /home/adam/dev/git/github/addwiki/addwiki/vendor/rector/rector/packages/NodeTypeResolver/PHPStan/Type/TypeFactory.php on line 156
Notice: Undefined offset: 1 in /home/adam/dev/git/github/addwiki/addwiki/vendor/rector/rector/packages/NodeTypeResolver/PHPStan/Type/TypeFactory.php on line 156
 362/792 [▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░]  45%PHP Notice:  Undefined offset: 1 in /home/adam/dev/git/github/addwiki/addwiki/vendor/rector/rector/packages/NodeTypeResolver/PHPStan/Type/TypeFactory.php on line 156
Notice: Undefined offset: 1 in /home/adam/dev/git/github/addwiki/addwiki/vendor/rector/rector/packages/NodeTypeResolver/PHPStan/Type/TypeFactory.php on line 156
PHP Notice:  Undefined offset: 2 in /home/adam/dev/git/github/addwiki/addwiki/vendor/rector/rector/packages/NodeTypeResolver/PHPStan/Type/TypeFactory.php on line 156
Notice: Undefined offset: 2 in /home/adam/dev/git/github/addwiki/addwiki/vendor/rector/rector/packages/NodeTypeResolver/PHPStan/Type/TypeFactory.php on line 156
PHP Notice:  Undefined offset: 2 in /home/adam/dev/git/github/addwiki/addwiki/vendor/rector/rector/packages/NodeTypeResolver/PHPStan/Type/TypeFactory.php on line 156
Notice: Undefined offset: 2 in /home/adam/dev/git/github/addwiki/addwiki/vendor/rector/rector/packages/NodeTypeResolver/PHPStan/Type/TypeFactory.php on line 156
PHP Notice:  Undefined offset: 3 in /home/adam/dev/git/github/addwiki/addwiki/vendor/rector/rector/packages/NodeTypeResolver/PHPStan/Type/TypeFactory.php on line 156
```

## Expected Behaviour

This notice should not happen

### PR DESCRIPTION
**Pull request by addshore**
Not sure how to test this currently as I still did not narrow
the issue down to some specific code or case (as I'm currently
encountering other issues that I'm investigating)

Fixes #5953

### CODE REVIEW

File: packages/NodeTypeResolver/PHPStan/Type/TypeFactory.php [hunk 1]
```diff
@@ -153,7 +153,12 @@ private function unwrapConstantArrayTypes(ConstantArrayType $constantArrayType):
 
         foreach ($flattenItemTypes as $position => $nestedFlattenItemType) {
             /** @var Type|null $nestedFlattenKeyType */
-            $nestedFlattenKeyType = $flattenKeyTypes[$position];
+            if (!array_key_exists($position, $flattenKeyTypes)) {
+                $nestedFlattenKeyType = null;
+            } else {
+                $nestedFlattenKeyType = $flattenKeyTypes[$position];
+            }
```
Comment (TomasVotruba) [inline packages/NodeTypeResolver/PHPStan/Type/TypeFactory.php:160]:
```suggestion
            $nestedFlattenKeyType = $flattenKeyTypes[$position] ?? null;
```

**Comment by TomasVotruba** [comment]
Thanks :+1:
